### PR TITLE
Change contact person for 23/24 period in Contact.vue file

### PR DESCRIPTION
**Pull request by vincentiusantu**
Since the Practicum Coordinators and the email changed,  I changed the contact person for 23/24 period in Contact.vue, here's the view of the page

## Before
image

## After
image

### CODE REVIEW

**Review by IritaSee — APPROVED** [review]
The code looks good to me, but the pull request is not informative enough. Try to see previous' PR in the `closed` PRs

**Comment by vincentiusantu** [comment]
> The code looks good to me, but the pull request is not informative enough. Try to see previous' PR in the `closed` PRs

Thanks for the review bang, I'll try to give information more specific in the next PR

**Review by Soedipo — APPROVED** [review]
It's good, but I aggree with bang @IritaSee , please make the information more specific.

**Comment by IritaSee** [comment]
Okay, that's good! I think @Soedipo should do the merge

**Comment by Soedipo** [comment]
> Okay, that's good! I think @Soedipo should do the merge

Okay, I'll merge it

**Pull request merged**
