### PR TITLE
Replace Unmatched Assistant Code Quick fix with more permanent fix, and UX improvement

### PR DESCRIPTION
**Pull request by IritaSee**
This quick PR raised because there is a **critical** frontend bug in our polling page. The chosen assistant code shown in the vote button does not match with the assistant code we choose. This frontend bug may cause the `allAsisten` array to be out of bounded. Last year, we fix this bug by decreasing the index value by 1 since the assistant database is sequential according to their Assistant ID. This condition does not occur this year since we need to delete some retired assistant's account.

So, this fix replace the assistant code showing method from showing by its occurrence in the `allAsisten` array to **Get JavaScript object from array of objects by value of property which is the assistant ID inside the array**

Also in this PR, I purposed a new text for the TP collection form. `Praktikan` seems don't understand the whole feature of TP form that also allow them to save the TP instead of directly submitting them, so I changed some text to match the developer's meaning that they can save their TP, not directly submit them.

Thank you and sorry in advance for this slow bug response

### CODE REVIEW

**Comment by IritaSee** [comment]
Oops i forget to add new assistants photo, wait let me push another one

**Comment by IritaSee** [comment]
I will reopen the PR after I update all assistant photos, probably this noon after 4th shift

**Comment by fakhrip** [comment]
Alright, btw just push to this same branch and it will automatically be added to this current PR (just in case you didnt know about it)

**Comment by IritaSee** [comment]
I already push it to this branch but it doesn't show up here

**Review by fakhrip — APPROVED** [review]
LGTM

**Pull request merged**
