### PR TITLE
Praktikum Sequence Change for 2020/21 Academic Year (pt.2)

### PR DESCRIPTION
**Pull request by IritaSee**
pt. 2 Made because the original PR had a conflict issue.

1) **Major Change:  For this semester the praktikum sequence changes from:**
 **TA->Jurnal->Mandiri->TK**
**to:**
**TA-> Presentasi -> Jurnal-> TK**
Presentasi contents are submitted TP where isProgram=1 (a.k.a. number 6,7,8 from praktikan's side). Each question picked randomly. Praktikan can select and edit their TP (Client side only and won't change TP answers in DB) while in presentasi. Presentasi uses the same timing like mandiri's timing

2) Implement html form (upload.blade.php) to upload photos for asisten. Meanwhile the feature described in number 1 is Mandatory, this minor feature will be enhanced soon with a vue frontend instead of a html form popup

3) Update the contacts form to new asprak on duty, and fixing some typo.

4) Make an endpoint to return praktikan's nilai according to nim and modul_id, implemented with API

5) FITB now no longer pops in random order, to maintain praktikan's desired output in each modul

### CODE REVIEW

**Comment by fakhrip** [comment]
Sorry i missed something, you actually have to merge master into `broken`(your branch) first then commit to the `broken` branch again

**Comment by fakhrip** [comment]
Hopefully this will fix the conflict problem @IritaSee , ill merge after this solved

**Comment by IritaSee** [comment]
I hope that solves the problem

**Review by fakhrip — APPROVED** [review]
LGTM

**Pull request merged**
