### PR TITLE
Remove TP Randomizer, and doing little following UI implementations 

### PR DESCRIPTION
**Pull request by IritaSee**
In this pull request, our `Practicum Manager` requests to utilize more TP question number 8 as the most challenging question for `Praktikan`. So we decide to ask the question again in `Presentasi` session. But unlike what we have implemented for the last semester, now we will show `Praktikan` 's Answer instead of ours. So I did some changes in the controller, in the frontend to match them, etc. The details are shown below:

0) Remove `InRandomOrder()` function when requesting `TP ` question so now `ATC` *Must* put questions in the right order
1) Change the `Presentasi` placeholder, do to it is a certain that we will show `Praktikan`'s answer for number 8
2) Add `Pajak` beside the `gaji` view in Assistant's `Profil`, so I did some change to the `show` function in `AsistenController`

I hope this is a good example of a pull request, because I currently learning git with a mentor from `google` now, he must be ashamed of me if I cannot do this request in the right way

### CODE REVIEW

**Comment by fakhrip** [comment]
> I hope this is a good example of a pull request, because I currently learning git with a mentor from google now, he must be ashamed of me if I cannot do this request in the right way

Im pretty sure he's not when he sees this PR :smile:

**Review by fakhrip — APPROVED** [review]
Nice, this is looking good to me, well played @IritaSee :+1:

**Comment by IritaSee** [comment]
Thank you so much, you really taught me to do this from scratch about this and you are a really good mentor. In fact i made him seeing this repo tho 😂

**Comment by fakhrip** [comment]
> Thank you so much, you really taught me to do this from scratch about this and you are a really good mentor. In fact i made him seeing this repo tho joy @fakhrip

Awesome, proud of you too man :+1:

**Pull request merged**
